"""empty message

Revision ID: 125fa94b4d8b
Revises: 40a8fa68efbc
Create Date: 2022-05-25 00:52:45.062384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125fa94b4d8b'
down_revision = '40a8fa68efbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('Artist_id', sa.Integer(), nullable=False))
    op.drop_column('Artist', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Artist_id_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.drop_column('Artist', 'Artist_id')
    # ### end Alembic commands ###
