"""empty message

Revision ID: 6f0d3f1a5f21
Revises: 28f153e224ef
Create Date: 2022-05-30 00:25:06.801638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0d3f1a5f21'
down_revision = '28f153e224ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'venue', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue', type_='unique')
    # ### end Alembic commands ###
