"""empty message

Revision ID: 7516d7d9f61c
Revises: 6f0d3f1a5f21
Create Date: 2022-05-30 21:01:30.194707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7516d7d9f61c'
down_revision = '6f0d3f1a5f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('id', sa.Integer(), nullable=True))
    op.drop_column('artist', 'artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('artist', 'id')
    # ### end Alembic commands ###
