"""empty message

Revision ID: 80333b78834d
Revises: e496ab01bc0c
Create Date: 2022-05-25 00:53:44.048718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80333b78834d'
down_revision = 'e496ab01bc0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('name', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('state', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('phone', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('image_link', sa.String(length=500), nullable=True))
    op.add_column('Artist', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('Artist', sa.Column('facebook_link', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('Artist', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    op.add_column('Artist', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'upcoming_shows_count')
    op.drop_column('Artist', 'past_shows_count')
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'facebook_link')
    op.drop_column('Artist', 'website')
    op.drop_column('Artist', 'image_link')
    op.drop_column('Artist', 'genres')
    op.drop_column('Artist', 'phone')
    op.drop_column('Artist', 'state')
    op.drop_column('Artist', 'city')
    op.drop_column('Artist', 'name')
    # ### end Alembic commands ###
