"""empty message

Revision ID: 879770785f7d
Revises: 235aec07fa25
Create Date: 2022-06-04 18:27:38.278526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879770785f7d'
down_revision = '235aec07fa25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shows', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('shows', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'shows', 'artist', ['artist_id'], ['artist_id'])
    op.create_foreign_key(None, 'shows', 'venue', ['venue_id'], ['venue_id'])
    op.drop_column('shows', 'artist_image_link')
    op.drop_column('shows', 'artist_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artist_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('artist_image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.alter_column('shows', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('shows', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
