"""empty message

Revision ID: a3a885715dff
Revises: ab5c579b6263
Create Date: 2022-06-01 04:56:07.617085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a3a885715dff'
down_revision = 'ab5c579b6263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('past_shows')
    op.drop_table('upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upcoming_shows',
    sa.Column('show_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('artist_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('artist_image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('show_id', name='upcoming_shows_pkey')
    )
    op.create_table('past_shows',
    sa.Column('show_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('artist_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('artist_image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('show_id', name='past_shows_pkey')
    )
    # ### end Alembic commands ###
