"""empty message

Revision ID: ae0dec17c3c2
Revises: 64acffceb50e
Create Date: 2022-05-25 00:56:22.328184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae0dec17c3c2'
down_revision = '64acffceb50e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.drop_column('artist', 'Artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('Artist_id', sa.INTEGER(), server_default=sa.text('nextval(\'"artist_Artist_id_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.drop_column('artist', 'artist_id')
    # ### end Alembic commands ###
